- src/test/resources/daniel.feature
> first commit

- src/test/resources/Anna_li.feature
> second change

- src/test/resources/daniel.feature
> 1. Cut your own branch from `master` locally, typing:
>     `git checkout -b name_of_your_branch`
>     and create remote copy
>     **`git push --set-upstream origin name_of_your_branch`**
In my version little bit different, its confused :
> 1. Cut your own branch from `master` locally, typing:
>     `git checkout -b name_of_your_branch`
>     and create remote copy
>     **`git name_of_your_branch`**
> MISTAKE IN README

- src/test/resources/vik.feature
A "pull request" is you requesting the target repository to please grab your changes. A "push request" would be the target repository requesting you to push your changes. When you send a pull request, you're asking (requesting) the official repo owner to pull some changes from your own repo. Hence "pull request".
> Why is it called a pull request?

- src/test/resources/features/testYulia.feature
> Test commit

- src/test/java/definifions/SingleChoiceQuiestionShowStopper.java
- src/test/java/definifions/userFirstName.java
- src/test/resources/feature/Objects/SingleChoiceQuestionShowStopper.feature
- src/test/resources/feature/Objects/UserFirstName.feature
> Olga ASK-636 first commit

- src/test/resources/Features/olga23march.feature
- src/test/resources/Features/olga24march.feature
> Olga24march

- src/test/java/definitions/registrationFirstName.java
- src/test/resources/features/RegistrationFirst name.feature
> changing definision file

- src/test/resources/Features/Lada3.feature
> was Deleted

- src/test/java/definitions/OlesiaDefenitionFile.java
- src/test/resources/features/OlesiaSingleChoiceQuestionText.feature
Automate test set "Single Choice Question - Text"
> Updated quiz single shoice

- src/test/java/definitions/title.java
- src/test/resources/features/quiz/title/title.feature
> Ap 476 automate title of quiz

- src/test/resources/features/seema123.feature
> seema123 feature file

- src/test/java/definitions/MultipleChoiceQuesText.java
- src/test/java/definitions/assignmentQuizName.java
- src/test/java/definitions/login.java
- src/test/resources/features/assignmentQuizName.feature
> assignment quiz-name DONE

- src/test/resources/features/anatoliyask.feature
> Anatoliy kon

- src/test/resources/features/helen.feature
created a file called helen.feature and made some changes in it
> added new feature file

- src/test/java/definitions/multipleChoiceQuestion.java
- src/test/resources/features/multChoiceQuestionOther.feature
New code for Multiple Choice Question with other field (feature + staging file)
Most steps used existing step file definitions
2 steps failed with existing code from GitHub so I created new steps in a new definition file for those 2 steps
> Pc ask master

- src/test/java/definitions/createquizAssigntoStudent.java
- src/test/java/definitions/editquizAssigntoStudent.java
- src/test/resources/Features/createquizAssigntoStudent.feature
- src/test/resources/Features/editquizAssigntoStudent.feature
1.Textual Question - Show-Stopper - at creating Quiz
2.Textual Question - Show-Stopper - at editing Quiz
> create update quiz assign to student

- src/test/java/definitions/quizTotalQuestions.java
- src/test/resources/Features/quizTotalQuestion.feature
> the greatest commit ever

- src/test/java/definitions/forgotPassword.java
- src/test/resources/Features/forgotPassword.feature
Please merge to master: test cases for forgotPassword
> [ADDED] forgotPassword feature file and step definitions

- src/test/resources/Features/testFileSaid.feature
First pull request; added one .feature file
> Said branch

- src/test/java/definitions/login.java
- src/test/java/definitions/usersManagmStGroup.java
- src/test/resources/Features/usersManagmStGroup.feature
AC-343 User's management - Options in Student's account - Change User's Group - Changed (Automated test)
> EO last task

- src/test/resources/features/NewFileMila.feature
> test commit june 13

- src/test/resources/features/testMe.feature
New .feature added. No other changes done.
> Beluga roars

- pom.xml
- src/test/resources/features/mytestfile.feature
- src/test/resources/features/mytestfile2.feature
> Edited mytestfile.feature scenario

- src/test/resources/features/mister_second.feature
> Igor Second Test

- src/test/resources/features/feature123.feature
- src/test/resources/features/newFeature.feature
> Revert "j1 added"

- src/test/resources/features/group1.feature
> natallia k resolved

- src/test/resources/features/registrationEmail.feature
Test Set "Registration - Email" created
> Test Set "Registration - Email" created

- src/test/resources/features/MyFileNat.feature
> My first commit
